server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-vue2?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: 088220

mybatis:
  mapper-locations:
    classpath:mapper/*.xml
# for mybatis
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# for mybatis plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: D:/work/JAVA/vue1/springboot/files/
